### ISSUE TITLE
Layout bug - tooltips options

### ISSUE THREAD

**Issue by movingwater** [flokosiol/kirby-subpagelist#10]
Does anybody else have this issue, that you can't use the tooltips option menu. It seems to be behind the listed pages. So the shortcuts options can't be used (see screenshot)
![bildschirmfoto 2017-12-07 um 14 08 09](https://user-images.githubusercontent.com/8091819/33717292-a56d7bbc-db59-11e7-8d24-e225cbb300fa.jpg)

I use the latest plugin version with kirby 2.5.7.

**Comment by flokosiol** [comment]
Mmmh … for me everything works fine. 
Latest Kirby 2.5.7, latest Subpagelist 2.0.4, Mac OS, Chrome 62

![bildschirmfoto 2017-12-07 um 16 21 28](https://user-images.githubusercontent.com/11918336/33722659-e494672c-db6a-11e7-9e6d-2d87d855c836.png)

What's your Browser? Does this error also occur in the sidebar? The [plugin uses](https://github.com/flokosiol/kirby-subpagelist/blob/master/subpagelist.php#L77) the [default Kirby sidebar snippet](https://github.com/getkirby/panel/blob/master/app/src/panel/models/page/sidebar.php#L47) for subpages without any template modification.

**Comment by movingwater** [comment]
Hi, the sidebar seem to be ok. I use it with Mac OS (10.13) with Chrome 62 or safari 11.

That's wired. Maybe it conflicts with the tabs plugin?

**Comment by flokosiol** [comment]
I'm also using tabs (tabs field) 🙈
https://github.com/afbora/Kirby-Tabs-Field

Does it work, if you create a blueprint with no other fields than the subpagelist?

**Comment by movingwater** [comment]
Just figured out, that it conflicts with the tabs field. If I remove every tab, it works correct. But as soon as I add a tab to the blueprint, the problem appears. 
I did reinstall the tabs field, but it didn't help.

**Comment by movingwater** [comment]
Now I think I found the problem. It's caused through the tabs field's css:
```css
.tab-container {
  /* display: none; causes the Kirby textarea to be unable to determine the correct */
  /* height to set itself too. It usually ends up too big. Instead, we move the div */
  /* off-screen so that the textarea can properly determine it's height */
  visibility: hidden;
  max-height: 0px;
  overflow: hidden;
  position: relative;
  z-index: 1;
  pointer-events: none;
  transform: translateX(-9999px);
}

.tab-container.active {
  visibility: visible;
  max-height: 9999px;
  overflow: visible;
  z-index: 2;
  pointer-events: auto;
  transform: none;
}
```
if I uncomment the two "z-index" parts, the tooltip is displayed correct. but it is wired that you, @flokosiol, have no problems?
