### ISSUE TITLE
Filter by multiple templates

### ISSUE THREAD

**Issue by dennisfrank** [flokosiol/kirby-subpagelist#4]
Great field plugin. Thanks!

Is it possible to filter by multiple categories? 

This does not work (for me):

```
...
fields:
    mysubpagelist:
        label: My Subpagelist
        type:  subpagelist

        flip:  true
        filter:
            visible: true
            template: 
                - mytemplate
                - myothertemplate
...
```
