### ISSUE TITLE
Can't get filterBy to work

### ISSUE THREAD

**Issue by jenstornell** [flokosiol/kirby-subpagelist#7]
Is this not correct in the blueprint?

``` yml
myfield:
    type:  subpagelist
    filter:
      filterBy:
        filterMethod: category
        filterValue: somevalue
```

**Comment by flokosiol** [comment]
I need to add an example to the README and with the naming I did not make the best choice 👎 

It works like https://getkirby.com/docs/cheatsheet/pages/filter-by 

```
$key = filterBy
$operator = filterMethod
$value = filterValue
```

 In the end it should look like this …

``` yml
myfield:
    type:  subpagelist
    filter:
      filterBy: category
      filterMethod: ==
      filterValue: somevalue
```
