### ISSUE TITLE
filterBy date - pages older than now

### ISSUE THREAD

**Issue by iskrisis** [flokosiol/kirby-subpagelist#8]
I would like to show only pages that have date older/newer than today.

```
  archived_events:
    label: Archived events
    type:  subpagelist
    filter:
      visible: true
      filterBy: date
      filterMethod: >
      filterValue: time()
```

Does not seem to do anything.

How to set filtervalue properly? And maybe i need escape filter method?
